[build]
  command = "npm run build"
  publish = ".output/public" # Use "dist" if using raw Vite/Vue 3 instead of Nuxt

[dev]
  command = "npm run dev"
  framework = "#custom"      # Forces Netlify not to guess and use your strict port overrides
  port = 5173                # The exact port Vite is launching on
  targetPort = 9000          # The port Netlify will expose to you to route requests